# SPDX-FileCopyrightText: (C) 2024 90degs2infty
# SPDX-FileContributor: 90degs2infty <90degs2infty@posteo.org>
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: Licensing

on: [push, pull_request]

jobs:
  reuse:
    name: REUSE compliance check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: fsfe/reuse-action@v3
